# Generated by Django 5.1.15 on 2026-08-30 08:56

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0002_initial"),
        ("inventory", "0001_initial"),
        ("ledger", "0001_initial"),
        ("parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                ("document_date", models.DateField(db_index=True)),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "posting_date",
                    models.DateField(
                        help_text="Ledger date; must fall inside an open fiscal period (BR-020)."
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1"), max_digits=18
                    ),
                ),
                (
                    "subtotal_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "line_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "document_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "rounding_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "subtotal_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "line_discount_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "document_discount_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "rounding_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "allocated_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "credited_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "open_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "open_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("POSTED", "Posted"),
                            ("PARTIAL", "Partially fulfilled / partially paid"),
                            ("COMPLETED", "Completed / paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REVERSED", "Reversed / credited"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_reason", models.CharField(blank=True, max_length=255)),
                ("expected_date", models.DateField(blank=True, null=True)),
                (
                    "customer_reference",
                    models.CharField(
                        blank=True,
                        help_text="Customer PO number (SAL-014).",
                        max_length=64,
                    ),
                ),
                ("billing_address_text", models.TextField(blank=True)),
                ("shipping_address_text", models.TextField(blank=True)),
                (
                    "document_discount_kind",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("PERCENT", "Percentage"),
                            ("AMOUNT", "Fixed amount"),
                        ],
                        default="NONE",
                        max_length=8,
                    ),
                ),
                (
                    "document_discount_value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="parties.customer",
                    ),
                ),
                (
                    "fiscal_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.fiscalperiod",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.paymentterm",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "salesperson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "sales_order",
                "ordering": ["-document_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SalesInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                ("document_date", models.DateField(db_index=True)),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "posting_date",
                    models.DateField(
                        help_text="Ledger date; must fall inside an open fiscal period (BR-020)."
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1"), max_digits=18
                    ),
                ),
                (
                    "subtotal_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "line_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "document_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "rounding_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "subtotal_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "line_discount_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "document_discount_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "rounding_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "allocated_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "credited_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "open_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "open_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("POSTED", "Posted"),
                            ("PARTIAL", "Partially fulfilled / partially paid"),
                            ("COMPLETED", "Completed / paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REVERSED", "Reversed / credited"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_reason", models.CharField(blank=True, max_length=255)),
                ("customer_reference", models.CharField(blank=True, max_length=64)),
                (
                    "customer_name_snapshot",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "customer_tax_id_snapshot",
                    models.CharField(blank=True, max_length=50),
                ),
                ("billing_address_text", models.TextField(blank=True)),
                ("shipping_address_text", models.TextField(blank=True)),
                (
                    "document_discount_kind",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("PERCENT", "Percentage"),
                            ("AMOUNT", "Fixed amount"),
                        ],
                        default="NONE",
                        max_length=8,
                    ),
                ),
                (
                    "document_discount_value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                ("is_reversed", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="parties.customer",
                    ),
                ),
                (
                    "fiscal_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.fiscalperiod",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.paymentterm",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receivable_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.account",
                    ),
                ),
                (
                    "reversed_by_journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="sales.salesorder",
                    ),
                ),
            ],
            options={
                "db_table": "sales_invoice",
                "ordering": ["-document_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SalesOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                (
                    "line_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "allocated_document_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_rate_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                ("tax_is_inclusive", models.BooleanField(default=False)),
                ("tax_is_recoverable", models.BooleanField(default=True)),
                (
                    "gross_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "net_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "net_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "quantity_delivered",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "quantity_invoiced",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "quantity_cancelled",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.taxcode",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.unitofmeasure",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "sales_order_line",
                "ordering": ["order", "line_no"],
            },
        ),
        migrations.CreateModel(
            name="SalesInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                (
                    "line_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "allocated_document_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_rate_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                ("tax_is_inclusive", models.BooleanField(default=False)),
                ("tax_is_recoverable", models.BooleanField(default=True)),
                (
                    "gross_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "net_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "net_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("product_sku_snapshot", models.CharField(blank=True, max_length=40)),
                (
                    "quantity_returned",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "delivery_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_lines",
                        to="inventory.deliverynoteline",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.salesinvoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "revenue_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.account",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.taxcode",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.unitofmeasure",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "sales_order_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sales.salesorderline",
                    ),
                ),
            ],
            options={
                "db_table": "sales_invoice_line",
                "ordering": ["invoice", "line_no"],
            },
        ),
        migrations.CreateModel(
            name="SalesReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                ("document_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("POSTED", "Posted"),
                            ("PARTIAL", "Partially fulfilled / partially paid"),
                            ("COMPLETED", "Completed / paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REVERSED", "Reversed / credited"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField(help_text="Mandatory (RET-008).")),
                (
                    "total_cost_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="parties.customer",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "original_delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="inventory.deliverynote",
                    ),
                ),
                (
                    "original_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="sales.salesinvoice",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "sales_return",
                "ordering": ["-document_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SalesCreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                ("document_date", models.DateField(db_index=True)),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "posting_date",
                    models.DateField(
                        help_text="Ledger date; must fall inside an open fiscal period (BR-020)."
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1"), max_digits=18
                    ),
                ),
                (
                    "subtotal_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "line_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "document_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "rounding_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "subtotal_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "line_discount_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "document_discount_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "rounding_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "allocated_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "credited_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "open_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "open_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("POSTED", "Posted"),
                            ("PARTIAL", "Partially fulfilled / partially paid"),
                            ("COMPLETED", "Completed / paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REVERSED", "Reversed / credited"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_reason", models.CharField(blank=True, max_length=255)),
                ("reason", models.TextField(help_text="Mandatory (RET-008).")),
                (
                    "customer_name_snapshot",
                    models.CharField(blank=True, max_length=200),
                ),
                ("billing_address_text", models.TextField(blank=True)),
                (
                    "refunded_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("is_reversed", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="parties.customer",
                    ),
                ),
                (
                    "fiscal_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.fiscalperiod",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="sales.salesinvoice",
                    ),
                ),
                (
                    "sales_return",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="sales.salesreturn",
                    ),
                ),
            ],
            options={
                "db_table": "sales_credit_note",
                "ordering": ["-document_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SalesReturnLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField()),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("RESTOCK", "Return to saleable stock"),
                            ("WRITE_OFF", "Damaged / write-off"),
                            ("NO_STOCK_EFFECT", "No stock effect"),
                        ],
                        default="RESTOCK",
                        max_length=16,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "delivery_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="inventory.deliverynoteline",
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="sales.salesinvoiceline",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "sales_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.salesreturn",
                    ),
                ),
            ],
            options={
                "db_table": "sales_return_line",
                "ordering": ["sales_return", "line_no"],
            },
        ),
        migrations.CreateModel(
            name="SalesCreditNoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                (
                    "line_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "allocated_document_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_rate_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                ("tax_is_inclusive", models.BooleanField(default=False)),
                ("tax_is_recoverable", models.BooleanField(default=True)),
                (
                    "gross_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "net_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "net_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "credit_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.salescreditnote",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "revenue_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.account",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.taxcode",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.unitofmeasure",
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_lines",
                        to="sales.salesinvoiceline",
                    ),
                ),
                (
                    "return_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sales.salesreturnline",
                    ),
                ),
            ],
            options={
                "db_table": "sales_credit_note_line",
                "ordering": ["credit_note", "line_no"],
            },
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["customer", "-document_date"], name="ix_so_customer_date"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["status", "-document_date"], name="ix_so_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["customer_reference"], name="ix_so_customer_ref"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)), name="so_rate_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_txn__gte", 0), ("total_base__gte", 0)),
                name="so_total_nonneg",
            ),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(
                fields=["customer", "-document_date"], name="ix_si_customer_date"
            ),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(fields=["status", "due_date"], name="ix_si_status_due"),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(fields=["posting_date"], name="ix_si_posting_date"),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(
                condition=models.Q(("open_txn__gt", 0)),
                fields=["customer", "due_date"],
                name="ix_si_open_items",
            ),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(
                fields=["currency", "status"], name="ix_si_currency_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)), name="si_rate_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_txn__gte", 0), ("total_base__gte", 0)),
                name="si_total_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allocated_txn__gte", 0),
                    ("credited_txn__gte", 0),
                    ("allocated_txn__lte", models.F("total_txn")),
                    ("credited_txn__lte", models.F("total_txn")),
                ),
                name="si_settlement_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("open_txn__gte", 0)), name="si_open_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "open_txn",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("total_txn"), "-", models.F("allocated_txn")
                            ),
                            "-",
                            models.F("credited_txn"),
                        ),
                    )
                ),
                name="si_open_is_derived",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["POSTED", "PARTIAL", "COMPLETED", "REVERSED"]),
                        _negated=True,
                    ),
                    ("journal_entry__isnull", False),
                    _connector="OR",
                ),
                name="si_posted_has_journal",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("due_date__isnull", True),
                    ("due_date__gte", models.F("document_date")),
                    _connector="OR",
                ),
                name="si_due_after_document_date",
            ),
        ),
        migrations.AddIndex(
            model_name="salesorderline",
            index=models.Index(fields=["product"], name="ix_so_line_product"),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.UniqueConstraint(
                fields=("order", "line_no"), name="so_line_unique_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="so_line_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)), name="so_line_price_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_percent__gte", 0), ("discount_percent__lte", 100)
                ),
                name="so_line_discount_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity_delivered__gte", 0), ("quantity_invoiced__gte", 0)
                ),
                name="so_line_fulfilment_nonneg",
            ),
        ),
        migrations.AddIndex(
            model_name="salesinvoiceline",
            index=models.Index(fields=["product"], name="ix_si_line_product"),
        ),
        migrations.AddIndex(
            model_name="salesinvoiceline",
            index=models.Index(fields=["tax_code"], name="ix_si_line_tax"),
        ),
        migrations.AddConstraint(
            model_name="salesinvoiceline",
            constraint=models.UniqueConstraint(
                fields=("invoice", "line_no"), name="si_line_unique_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="si_line_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)), name="si_line_price_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("line_discount_txn__gte", 0),
                    ("allocated_document_discount_txn__gte", 0),
                ),
                name="si_line_discount_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("line_discount_txn__lte", models.F("gross_txn"))),
                name="si_line_discount_within_gross",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity_returned__gte", 0),
                    ("quantity_returned__lte", models.F("quantity")),
                ),
                name="si_line_returned_within_invoiced",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tax_rate_percent__gte", 0), ("tax_rate_percent__lte", 100)
                ),
                name="si_line_tax_rate_range",
            ),
        ),
        migrations.AddIndex(
            model_name="salesreturn",
            index=models.Index(
                fields=["customer", "-document_date"], name="ix_sr_customer_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesreturn",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("original_invoice__isnull", False),
                    ("original_delivery__isnull", False),
                    _connector="OR",
                ),
                name="sales_return_has_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesreturn",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason", ""), _negated=True),
                name="sales_return_reason_required",
            ),
        ),
        migrations.AddIndex(
            model_name="salescreditnote",
            index=models.Index(
                fields=["customer", "-document_date"], name="ix_cn_customer_date"
            ),
        ),
        migrations.AddIndex(
            model_name="salescreditnote",
            index=models.Index(
                condition=models.Q(("open_txn__gt", 0)),
                fields=["customer"],
                name="ix_cn_open_credit",
            ),
        ),
        migrations.AddConstraint(
            model_name="salescreditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)), name="cn_rate_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="salescreditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_txn__gte", 0)), name="cn_total_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="salescreditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allocated_txn__gte", 0),
                    ("refunded_txn__gte", 0),
                    ("allocated_txn__lte", models.F("total_txn")),
                    ("refunded_txn__lte", models.F("total_txn")),
                ),
                name="cn_settlement_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="salescreditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "open_txn",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("total_txn"), "-", models.F("allocated_txn")
                            ),
                            "-",
                            models.F("refunded_txn"),
                        ),
                    )
                ),
                name="cn_open_is_derived",
            ),
        ),
        migrations.AddConstraint(
            model_name="salescreditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(("open_txn__gte", 0)), name="cn_open_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="salescreditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["POSTED", "PARTIAL", "COMPLETED", "REVERSED"]),
                        _negated=True,
                    ),
                    ("journal_entry__isnull", False),
                    _connector="OR",
                ),
                name="cn_posted_has_journal",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesreturnline",
            constraint=models.UniqueConstraint(
                fields=("sales_return", "line_no"), name="sr_line_unique_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesreturnline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="sr_line_qty_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="salescreditnoteline",
            index=models.Index(fields=["product"], name="ix_cn_line_product"),
        ),
        migrations.AddConstraint(
            model_name="salescreditnoteline",
            constraint=models.UniqueConstraint(
                fields=("credit_note", "line_no"), name="cn_line_unique_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="salescreditnoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="cn_line_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="salescreditnoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tax_rate_percent__gte", 0), ("tax_rate_percent__lte", 100)
                ),
                name="cn_line_tax_rate_range",
            ),
        ),
    ]
