# Generated by Django 5.2.17 on 2026-09-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescreditnote',
            name='posting_date',
            field=models.DateField(help_text='The date this document hits the ledger. It must fall inside an open fiscal period, and it can differ from the document date.'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='posting_date',
            field=models.DateField(help_text='The date this document hits the ledger. It must fall inside an open fiscal period, and it can differ from the document date.'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer_reference',
            field=models.CharField(blank=True, help_text='The customer’s own purchase order number, printed on their invoice.', max_length=64),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='posting_date',
            field=models.DateField(help_text='The date this document hits the ledger. It must fall inside an open fiscal period, and it can differ from the document date.'),
        ),
    ]
