# Generated by Django 5.1.15 on 2026-08-30 08:56

import apps.core.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_extensions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "rate_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                (
                    "is_inclusive",
                    models.BooleanField(
                        default=False,
                        help_text="Price entered already contains the tax (FTD-006).",
                    ),
                ),
                (
                    "is_recoverable",
                    models.BooleanField(
                        default=True,
                        help_text="Input tax may be reclaimed (drives input-tax reporting).",
                    ),
                ),
                (
                    "treatment",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard rated"),
                            ("ZERO_RATED", "Zero rated"),
                            ("EXEMPT", "Exempt"),
                            ("NO_TAX", "Out of scope / no tax"),
                        ],
                        default="STANDARD",
                        max_length=12,
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("SALES", "Sales only"),
                            ("PURCHASE", "Purchase only"),
                            ("BOTH", "Sales and purchase"),
                        ],
                        default="BOTH",
                        max_length=8,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tax_code",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("SUBMIT", "Submit"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("POST", "Post"),
                            ("REVERSE", "Reverse"),
                            ("ALLOCATE", "Allocate"),
                            ("UNALLOCATE", "Unallocate"),
                            ("CLOSE_PERIOD", "Close period"),
                            ("REOPEN_PERIOD", "Reopen period"),
                            ("EXPORT", "Export"),
                            ("LOGIN", "Login"),
                        ],
                        max_length=16,
                    ),
                ),
                ("object_id", models.BigIntegerField(blank=True, null=True)),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text='{"field": {"from": x, "to": y}} (ACC-005)',
                        null=True,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "correlation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_event",
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="ISO 4217",
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("symbol", models.CharField(blank=True, max_length=8)),
                ("decimal_places", models.PositiveSmallIntegerField(default=2)),
                (
                    "is_base",
                    models.BooleanField(
                        default=False,
                        help_text="Exactly one currency is the base currency (BR-002).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "currency",
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_base", True)),
                        fields=("is_base",),
                        name="currency_single_base",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("decimal_places__lte", 6)),
                        name="currency_decimal_places_sane",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("singleton", models.BooleanField(default=True, editable=False)),
                ("name", models.CharField(max_length=200)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                ("tax_id", models.CharField(blank=True, max_length=50)),
                ("registration_no", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("address_line1", models.CharField(blank=True, max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="company/"),
                ),
                (
                    "fiscal_year_start_month",
                    models.PositiveSmallIntegerField(default=1),
                ),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("language", models.CharField(default="en", max_length=10)),
                ("allow_negative_stock", models.BooleanField(default=False)),
                (
                    "rounding_tolerance",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.05"), max_digits=18
                    ),
                ),
                ("price_decimal_places", models.PositiveSmallIntegerField(default=2)),
                ("qty_decimal_places", models.PositiveSmallIntegerField(default=2)),
                ("require_po_approval", models.BooleanField(default=True)),
                ("require_so_approval", models.BooleanField(default=True)),
                ("block_duplicate_vendor_invoice", models.BooleanField(default=True)),
                ("warn_duplicate_customer_ref", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "base_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "company",
                "db_table": "company",
            },
        ),
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("SO", "Sales order"),
                            ("DN", "Delivery note"),
                            ("SI", "Sales invoice"),
                            ("SR", "Sales return"),
                            ("CN", "Sales credit note"),
                            ("PO", "Purchase order"),
                            ("GR", "Goods receipt"),
                            ("PB", "Purchase bill"),
                            ("PR", "Purchase return"),
                            ("DBN", "Vendor debit note"),
                            ("RC", "Customer receipt"),
                            ("PV", "Vendor payment"),
                            ("RF", "Refund"),
                            ("JE", "Journal entry"),
                            ("ST", "Stock transfer"),
                            ("SA", "Stock adjustment"),
                        ],
                        max_length=4,
                    ),
                ),
                ("series", models.CharField(default="DEFAULT", max_length=20)),
                ("prefix", models.CharField(blank=True, max_length=20)),
                ("suffix", models.CharField(blank=True, max_length=20)),
                ("padding", models.PositiveSmallIntegerField(default=5)),
                ("next_number", models.BigIntegerField(default=1)),
                (
                    "reset_policy",
                    models.CharField(
                        choices=[
                            ("NEVER", "Never"),
                            ("YEARLY", "Each fiscal year"),
                            ("MONTHLY", "Each month"),
                        ],
                        default="YEARLY",
                        max_length=8,
                    ),
                ),
                (
                    "period_key",
                    models.CharField(
                        blank=True,
                        help_text="Marks which year/month next_number belongs to.",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "document_sequence",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document_type", "series"),
                        name="document_sequence_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("next_number__gte", 1)),
                        name="document_sequence_next_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate_date", models.DateField()),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-8"))
                        ],
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=64)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates",
                        to="core.currency",
                    ),
                ),
            ],
            options={
                "db_table": "exchange_rate",
                "ordering": ["currency", "-rate_date"],
            },
        ),
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("LOCKED", "Permanently locked"),
                        ],
                        default="OPEN",
                        max_length=8,
                    ),
                ),
            ],
            options={
                "db_table": "fiscal_year",
                "ordering": ["start_date"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gt", models.F("start_date"))),
                        name="fiscal_year_dates_ordered",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[
                            (
                                apps.core.models.DateRangeInclusive(
                                    "start_date",
                                    "end_date",
                                    django.contrib.postgres.fields.ranges.RangeBoundary(
                                        inclusive_lower=True, inclusive_upper=True
                                    ),
                                ),
                                "&&",
                            )
                        ],
                        name="fiscal_year_no_overlap",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FiscalPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_no", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("LOCKED", "Permanently locked"),
                        ],
                        default="OPEN",
                        max_length=8,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("close_reason", models.TextField(blank=True)),
                ("reopened_at", models.DateTimeField(blank=True, null=True)),
                ("reopen_reason", models.TextField(blank=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reopened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periods",
                        to="core.fiscalyear",
                    ),
                ),
            ],
            options={
                "db_table": "fiscal_period",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("net_days", models.PositiveSmallIntegerField(default=0)),
                ("end_of_month", models.BooleanField(default=False)),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                ("discount_days", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "payment_term",
                "ordering": ["code"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("discount_percent__gte", 0), ("discount_percent__lte", 100)
                        ),
                        name="payment_term_discount_range",
                    )
                ],
            },
        ),
    ]
