# Generated by Django 5.1.15 on 2026-08-30 08:56

import apps.core.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxcode",
            name="input_tax_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ledger.account",
            ),
        ),
        migrations.AddField(
            model_name="taxcode",
            name="output_tax_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ledger.account",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["content_type", "object_id"], name="ix_audit_target"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["user", "-occurred_at"], name="ix_audit_user_time"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["action", "-occurred_at"], name="ix_audit_action_time"
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                fields=("singleton",), name="company_singleton"
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fiscal_year_start_month__gte", 1),
                    ("fiscal_year_start_month__lte", 12),
                ),
                name="company_fy_start_month_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                condition=models.Q(("rounding_tolerance__gte", 0)),
                name="company_rounding_tolerance_nonneg",
            ),
        ),
        migrations.AddIndex(
            model_name="exchangerate",
            index=models.Index(fields=["currency", "-rate_date"], name="ix_fx_lookup"),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.UniqueConstraint(
                fields=("currency", "rate_date"), name="exchange_rate_unique_per_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate__gt", 0)), name="exchange_rate_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(
                fields=["start_date", "end_date"], name="ix_period_daterange"
            ),
        ),
        migrations.AddIndex(
            model_name="fiscalperiod",
            index=models.Index(fields=["status"], name="ix_period_status"),
        ),
        migrations.AddConstraint(
            model_name="fiscalperiod",
            constraint=models.UniqueConstraint(
                fields=("fiscal_year", "period_no"), name="fiscal_period_unique_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="fiscal_period_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "OPEN"), ("closed_by__isnull", False), _connector="OR"
                ),
                name="fiscal_period_closed_has_actor",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalperiod",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("fiscal_year", "="),
                    (
                        apps.core.models.DateRangeInclusive(
                            "start_date",
                            "end_date",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                        ),
                        "&&",
                    ),
                ],
                name="fiscal_period_no_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxcode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rate_percent__gte", 0), ("rate_percent__lte", 100)
                ),
                name="tax_code_rate_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxcode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("treatment", "STANDARD"), ("rate_percent", 0), _connector="OR"
                ),
                name="tax_code_nonstandard_is_zero",
            ),
        ),
    ]
