# Generated by Django 5.2.17 on 2026-09-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_harden_public_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='changes',
            field=models.JSONField(blank=True, help_text='Which fields changed, with the value before and after each one.', null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_base',
            field=models.BooleanField(default=False, help_text='The currency your accounts are reported in. Exactly one currency can be the base, and changing it re-values every open balance.'),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='is_inclusive',
            field=models.BooleanField(default=False, help_text='Tick when prices are quoted with this tax already in them, so the tax is worked back out of the price rather than added to it.'),
        ),
    ]
