# Generated by Django 5.2.17 on 2026-09-04 01:09

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_seed_stripe_settlement"),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Shown on printed documents. PNG or JPEG, up to 2 MB.', null=True, upload_to='company/', validators=[apps.core.models.validate_logo_size]),
        ),
    ]
