# Generated by Django 5.1.15 on 2026-09-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_grant_sales_credit_note_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systempermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('approve_sales_order', 'Can approve or reject a sales order'), ('approve_purchase_order', 'Can approve or reject a purchase order'), ('approve_sales_return', 'Can approve a customer return'), ('approve_sales_credit_note', 'Can approve a sales credit note'), ('approve_stock_adjustment', 'Can approve a stock adjustment'), ('approve_refund', 'Can approve a refund'), ('post_sales_invoice', 'Can post a sales invoice'), ('post_purchase_bill', 'Can post a purchase bill'), ('post_delivery', 'Can post a delivery note'), ('post_sales_return', 'Can post a customer return'), ('post_goods_receipt', 'Can post a goods receipt'), ('post_payment', 'Can post a receipt or payment'), ('post_credit_note', 'Can post a sales credit note'), ('post_debit_note', 'Can post a vendor debit note'), ('post_stock_movement', 'Can post a stock transfer or adjustment'), ('post_journal', 'Can post a manual journal entry'), ('allocate_payment', 'Can allocate a payment or credit'), ('issue_refund', 'Can issue a refund'), ('reverse_document', 'Can reverse a posted document'), ('close_period', 'Can close a fiscal period'), ('reopen_period', 'Can reopen a closed fiscal period'), ('manage_configuration', 'Can change company and financial configuration'), ('manage_chart_of_accounts', 'Can change the chart of accounts and mappings'), ('view_audit_log', 'Can view the audit history'), ('export_data', 'Can export reports and lists'), ('view_financial_reports', 'Can view financial statements'), ('override_credit_hold', 'Can sell to a customer on credit hold'), ('override_negative_stock', 'Can post a movement that takes stock negative'), ('override_duplicate_vendor_invoice', 'Can accept a duplicate vendor invoice number'), ('override_return_quantity', 'Can return more than the eligible quantity'), ('override_exchange_rate', 'Can override the exchange rate for a transaction')], 'verbose_name': 'system permission', 'verbose_name_plural': 'system permissions'},
        ),
    ]
