# Generated by Django 5.2.17 on 2026-09-02 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_humanise_help_text'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='currency',
            field=models.ForeignKey(help_text='Used on new documents for this party. Individual documents can still be raised in another currency.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='currency',
            field=models.ForeignKey(help_text='Used on new documents for this party. Individual documents can still be raised in another currency.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency'),
        ),
    ]
