# Generated by Django 5.1.15 on 2026-08-30 08:56

import apps.core.expressions
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.lookups
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_initial"),
        ("ledger", "0001_initial"),
        ("parties", "0001_initial"),
        ("purchases", "0001_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneyAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash on hand"),
                            ("BANK", "Bank account"),
                            ("CARD", "Card / merchant account"),
                            ("OTHER", "Other"),
                        ],
                        default="BANK",
                        max_length=6,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=64)),
                ("iban", models.CharField(blank=True, max_length=64)),
                ("swift", models.CharField(blank=True, max_length=20)),
                ("allow_negative_balance", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
                (
                    "gl_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="money_accounts",
                        to="ledger.account",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "money_account",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Customer receipt (money in)"),
                            ("PAYMENT", "Vendor payment (money out)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("payment_date", models.DateField(db_index=True)),
                ("posting_date", models.DateField()),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1"), max_digits=18
                    ),
                ),
                ("amount_txn", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "amount_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "allocated_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "unallocated_txn",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Advance / unapplied credit (PAY-004, BR-009).",
                        max_digits=18,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=64)),
                ("narration", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("POSTED", "Posted"),
                            ("PARTIAL", "Partially fulfilled / partially paid"),
                            ("COMPLETED", "Completed / paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REVERSED", "Reversed / credited"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("is_reversed", models.BooleanField(default=False)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("reversal_reason", models.TextField(blank=True)),
                ("voucher_printed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="parties.customer",
                    ),
                ),
                (
                    "fiscal_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.fiscalperiod",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "money_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="payments.moneyaccount",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="parties.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "payment",
                "ordering": ["-payment_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allocation_date", models.DateField(db_index=True)),
                (
                    "party_side",
                    models.CharField(
                        choices=[("CUSTOMER", "Customer"), ("VENDOR", "Vendor")],
                        max_length=8,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT", "Payment"),
                            ("SALES_CREDIT_NOTE", "Sales credit note"),
                            ("VENDOR_DEBIT_NOTE", "Vendor debit note"),
                        ],
                        max_length=18,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("SALES_INVOICE", "Sales invoice"),
                            ("PURCHASE_BILL", "Purchase bill"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "source_amount_txn",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "target_amount_txn",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "amount_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "settlement_rate",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1"), max_digits=18
                    ),
                ),
                (
                    "fx_gain_loss_base",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Positive = gain, negative = loss (BR-014).",
                        max_digits=18,
                    ),
                ),
                ("is_reversed", models.BooleanField(default=False)),
                ("reversal_reason", models.CharField(blank=True, max_length=255)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="parties.customer",
                    ),
                ),
                (
                    "fx_journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when the allocation itself posts (credit application).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "purchase_bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="purchases.purchasebill",
                    ),
                ),
                (
                    "sales_credit_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="sales.salescreditnote",
                    ),
                ),
                (
                    "sales_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="sales.salesinvoice",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="parties.vendor",
                    ),
                ),
                (
                    "vendor_debit_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="purchases.vendordebitnote",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "payment_allocation",
                "ordering": ["-allocation_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "requires_reference",
                    models.BooleanField(
                        default=False,
                        help_text="Cheque number, transfer reference, card auth code.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_money_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="payments.moneyaccount",
                    ),
                ),
            ],
            options={
                "db_table": "payment_method",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="payments.paymentmethod",
            ),
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("TO_CUSTOMER", "Refund paid to customer"),
                            ("FROM_VENDOR", "Refund received from vendor"),
                        ],
                        max_length=12,
                    ),
                ),
                ("refund_date", models.DateField(db_index=True)),
                ("posting_date", models.DateField()),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1"), max_digits=18
                    ),
                ),
                ("amount_txn", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "amount_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=64)),
                ("reason", models.TextField(help_text="Mandatory (RET-008).")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("POSTED", "Posted"),
                            ("PARTIAL", "Partially fulfilled / partially paid"),
                            ("COMPLETED", "Completed / paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REVERSED", "Reversed / credited"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="parties.customer",
                    ),
                ),
                (
                    "fiscal_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.fiscalperiod",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.paymentmethod",
                    ),
                ),
                (
                    "money_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.moneyaccount",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_credit_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="sales.salescreditnote",
                    ),
                ),
                (
                    "source_payment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Refund of an unapplied advance.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="parties.vendor",
                    ),
                ),
                (
                    "vendor_debit_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="purchases.vendordebitnote",
                    ),
                ),
            ],
            options={
                "db_table": "refund",
                "ordering": ["-refund_date", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="moneyaccount",
            constraint=models.UniqueConstraint(
                fields=("gl_account",), name="money_account_gl_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(fields=["sales_invoice"], name="ix_alloc_invoice"),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(fields=["purchase_bill"], name="ix_alloc_bill"),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(fields=["payment"], name="ix_alloc_payment"),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(
                fields=["customer", "allocation_date"], name="ix_alloc_customer"
            ),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(
                fields=["vendor", "allocation_date"], name="ix_alloc_vendor"
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_amount_txn__gt", 0), ("target_amount_txn__gt", 0)
                ),
                name="allocation_amounts_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("settlement_rate__gt", 0)),
                name="allocation_rate_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    apps.core.expressions.NumNonnulls(
                        models.F("payment"),
                        models.F("sales_credit_note"),
                        models.F("vendor_debit_note"),
                    ),
                    models.Value(1),
                ),
                name="allocation_exactly_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    apps.core.expressions.NumNonnulls(
                        models.F("sales_invoice"), models.F("purchase_bill")
                    ),
                    models.Value(1),
                ),
                name="allocation_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    apps.core.expressions.NumNonnulls(
                        models.F("customer"), models.F("vendor")
                    ),
                    models.Value(1),
                ),
                name="allocation_exactly_one_party",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source_type", "PAYMENT"), ("payment__isnull", False)),
                    models.Q(
                        ("source_type", "SALES_CREDIT_NOTE"),
                        ("sales_credit_note__isnull", False),
                    ),
                    models.Q(
                        ("source_type", "VENDOR_DEBIT_NOTE"),
                        ("vendor_debit_note__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="allocation_source_matches_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("target_type", "SALES_INVOICE"),
                        ("sales_invoice__isnull", False),
                    ),
                    models.Q(
                        ("target_type", "PURCHASE_BILL"),
                        ("purchase_bill__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="allocation_target_matches_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("party_side", "CUSTOMER"), ("customer__isnull", False)),
                    models.Q(("party_side", "VENDOR"), ("vendor__isnull", False)),
                    _connector="OR",
                ),
                name="allocation_party_matches_side",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("party_side", "CUSTOMER"),
                        ("target_type", "SALES_INVOICE"),
                        ("source_type__in", ["PAYMENT", "SALES_CREDIT_NOTE"]),
                    ),
                    models.Q(
                        ("party_side", "VENDOR"),
                        ("target_type", "PURCHASE_BILL"),
                        ("source_type__in", ["PAYMENT", "VENDOR_DEBIT_NOTE"]),
                    ),
                    _connector="OR",
                ),
                name="allocation_side_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_reversed", False),
                    ("payment__isnull", False),
                    ("sales_invoice__isnull", False),
                ),
                fields=("payment", "sales_invoice"),
                name="allocation_unique_payment_invoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_reversed", False),
                    ("payment__isnull", False),
                    ("purchase_bill__isnull", False),
                ),
                fields=("payment", "purchase_bill"),
                name="allocation_unique_payment_bill",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_reversed", False), ("sales_credit_note__isnull", False)
                ),
                fields=("sales_credit_note", "sales_invoice"),
                name="allocation_unique_credit_invoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_reversed", False), ("vendor_debit_note__isnull", False)
                ),
                fields=("vendor_debit_note", "purchase_bill"),
                name="allocation_unique_debit_bill",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["customer", "-payment_date"], name="ix_pay_customer_date"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["vendor", "-payment_date"], name="ix_pay_vendor_date"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["money_account", "-payment_date"], name="ix_pay_money_date"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "-payment_date"], name="ix_pay_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                condition=models.Q(("unallocated_txn__gt", 0)),
                fields=["customer", "vendor"],
                name="ix_pay_unapplied",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("direction", "RECEIPT"),
                        ("customer__isnull", False),
                        ("vendor__isnull", True),
                    ),
                    models.Q(
                        ("direction", "PAYMENT"),
                        ("vendor__isnull", False),
                        ("customer__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="payment_party_matches_direction",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_txn__gt", 0)),
                name="payment_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)),
                name="payment_rate_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allocated_txn__gte", 0),
                    ("allocated_txn__lte", models.F("amount_txn")),
                ),
                name="payment_allocated_within_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "unallocated_txn",
                        django.db.models.expressions.CombinedExpression(
                            models.F("amount_txn"), "-", models.F("allocated_txn")
                        ),
                    )
                ),
                name="payment_unallocated_is_derived",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("unallocated_txn__gte", 0)),
                name="payment_unallocated_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["POSTED", "PARTIAL", "COMPLETED", "REVERSED"]),
                        _negated=True,
                    ),
                    ("journal_entry__isnull", False),
                    _connector="OR",
                ),
                name="payment_posted_has_journal",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_reversed", False),
                    models.Q(
                        ("reversed_by__isnull", False),
                        models.Q(("reversal_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="payment_reversal_attributable",
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["customer", "-refund_date"], name="ix_refund_customer"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["vendor", "-refund_date"], name="ix_refund_vendor"
            ),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(
                fields=["money_account", "-refund_date"], name="ix_refund_money"
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_txn__gt", 0)), name="refund_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)),
                name="refund_rate_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("direction", "TO_CUSTOMER"),
                        ("customer__isnull", False),
                        ("vendor__isnull", True),
                    ),
                    models.Q(
                        ("direction", "FROM_VENDOR"),
                        ("vendor__isnull", False),
                        ("customer__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="refund_party_matches_direction",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    apps.core.expressions.NumNonnulls(
                        models.F("sales_credit_note"),
                        models.F("vendor_debit_note"),
                        models.F("source_payment"),
                    ),
                    models.Value(1),
                ),
                name="refund_exactly_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["POSTED", "COMPLETED", "REVERSED"]),
                        _negated=True,
                    ),
                    ("journal_entry__isnull", False),
                    _connector="OR",
                ),
                name="refund_posted_has_journal",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason", ""), _negated=True),
                name="refund_reason_required",
            ),
        ),
    ]
