# Generated by Django 5.2.17 on 2026-09-02 10:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='fx_gain_loss_base',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Exchange difference realised when this payment settled, against the rate on the original document. Positive is a gain.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='payment',
            name='unallocated_txn',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Money received but not yet matched to an invoice. It sits as a credit on the account until it is allocated.', max_digits=18),
        ),
    ]
