# Generated by Django 5.2.17 on 2026-09-02 17:02

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_humanise_help_text'),
        ('parties', '0002_humanise_help_text'),
        ('payments', '0002_humanise_help_text'),
        ('purchases', '0002_humanise_help_text'),
        ('sales', '0002_humanise_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='allocation',
            name='allocation_unique_payment_invoice',
        ),
        migrations.RemoveConstraint(
            model_name='allocation',
            name='allocation_unique_payment_bill',
        ),
        migrations.RemoveConstraint(
            model_name='allocation',
            name='allocation_unique_credit_invoice',
        ),
        migrations.RemoveConstraint(
            model_name='allocation',
            name='allocation_unique_debit_bill',
        ),
        migrations.AddField(
            model_name='allocation',
            name='batch_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Idempotency key shared by every line submitted in one allocation request.'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_base__gt', 0)), name='allocation_base_positive'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reversed', False), ('payment__isnull', False), ('sales_invoice__isnull', False)), fields=('batch_key', 'payment', 'sales_invoice'), name='alloc_batch_payment_invoice_unique'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reversed', False), ('payment__isnull', False), ('purchase_bill__isnull', False)), fields=('batch_key', 'payment', 'purchase_bill'), name='alloc_batch_payment_bill_unique'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reversed', False), ('sales_credit_note__isnull', False)), fields=('batch_key', 'sales_credit_note', 'sales_invoice'), name='alloc_batch_credit_invoice_unique'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reversed', False), ('vendor_debit_note__isnull', False)), fields=('batch_key', 'vendor_debit_note', 'purchase_bill'), name='alloc_batch_debit_bill_unique'),
        ),
    ]
