# Generated by Django 5.2.17 on 2026-09-03 10:07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_humanise_help_text'),
        ('ledger', '0005_alter_accountmapping_key'),
        ('parties', '0002_humanise_help_text'),
        ('payments', '0004_allocation_consistency_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fee_base',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='payment',
            name='fee_txn',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Processor or bank fee, in the payment currency. Deducted from a customer receipt before the money lands; added to a vendor payment on top of what the vendor receives. Leave at zero when there is no fee.', max_digits=18),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('fee_txn__gte', 0), ('fee_base__gte', 0)), name='payment_fee_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('direction', 'PAYMENT'), ('fee_txn__lt', models.F('amount_txn')), _connector='OR'), name='payment_receipt_fee_below_amount'),
        ),
    ]
