# Generated by Django 5.2.17 on 2026-09-03 10:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_seed_stripe_settlement"),
        ('payments', '0005_payment_fee_base_payment_fee_txn_and_more'),
        ('sales', '0002_humanise_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('charge_id', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, help_text='The hosted Stripe page. Stripe expires this before the session itself.', max_length=1000)),
                ('amount_txn', models.DecimalField(decimal_places=4, help_text="What the link was created for - the invoice's open amount.", max_digits=18)),
                ('fee_txn', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='What Stripe kept, once settlement reports it.', max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting for the customer to pay'), ('PAID', 'Paid'), ('EXPIRED', 'Expired unpaid')], db_index=True, default='PENDING', max_length=8)),
                ('settlement_error', models.TextField(blank=True, help_text='Set when the customer paid but the receipt could not be posted - a closed period, a missing account mapping, no exchange rate for the day. The money arrived regardless; the ledger entry is outstanding.')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stripe_checkouts', to='sales.salesinvoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stripe_checkouts', to='payments.payment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stripe_checkout',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['invoice', '-created_at'], name='ix_stripe_invoice'), models.Index(condition=models.Q(('status', 'PAID'), ('payment__isnull', True)), fields=['-created_at'], name='ix_stripe_unsettled')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_txn__gt', 0)), name='stripe_checkout_amount_positive'), models.CheckConstraint(condition=models.Q(('fee_txn__gte', 0)), name='stripe_checkout_fee_nonneg'), models.CheckConstraint(condition=models.Q(('payment__isnull', True), ('status', 'PAID'), _connector='OR'), name='stripe_checkout_payment_needs_paid')],
            },
        ),
    ]
