# Generated by Django 5.1.15 on 2026-08-30 08:56

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdjustmentReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("increases_stock", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "adjustment_reason",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                ("document_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("POSTED", "Posted"),
                            ("PARTIAL", "Partially fulfilled / partially paid"),
                            ("COMPLETED", "Completed / paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REVERSED", "Reversed / credited"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_cost_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("shipping_address_text", models.TextField(blank=True)),
                ("carrier", models.CharField(blank=True, max_length=100)),
                ("tracking_reference", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "db_table": "delivery_note",
                "ordering": ["-document_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryNoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        help_text="Average cost at posting.",
                        max_digits=18,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "quantity_invoiced",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "quantity_returned",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
            ],
            options={
                "db_table": "delivery_note_line",
                "ordering": ["delivery", "line_no"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                ("document_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("POSTED", "Posted"),
                            ("PARTIAL", "Partially fulfilled / partially paid"),
                            ("COMPLETED", "Completed / paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REVERSED", "Reversed / credited"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_cost_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("vendor_delivery_note", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "db_table": "goods_receipt",
                "ordering": ["-document_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "quantity_received",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "quantity_accepted",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "quantity_rejected",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "quantity_billed",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "quantity_returned",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
            ],
            options={
                "db_table": "goods_receipt_line",
                "ordering": ["receipt", "line_no"],
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                ("document_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("POSTED", "Posted"),
                            ("PARTIAL", "Partially fulfilled / partially paid"),
                            ("COMPLETED", "Completed / paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REVERSED", "Reversed / credited"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("narration", models.TextField(blank=True)),
                ("attachment_reference", models.CharField(blank=True, max_length=255)),
                (
                    "total_value_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "stock_adjustment",
                "ordering": ["-document_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StockAdjustmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField()),
                (
                    "quantity_delta",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Signed: positive increases stock, negative decreases it.",
                        max_digits=18,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "value_delta",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "stock_adjustment_line",
                "ordering": ["adjustment", "line_no"],
            },
        ),
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "quantity_reserved",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("last_movement_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "stock_balance",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movement_date", models.DateField(db_index=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("GOODS_RECEIPT", "Goods receipt"),
                            ("DELIVERY", "Delivery"),
                            ("SALES_RETURN_IN", "Sales return (restock)"),
                            ("PURCHASE_RETURN_OUT", "Purchase return to vendor"),
                            ("TRANSFER_OUT", "Transfer out"),
                            ("TRANSFER_IN", "Transfer in"),
                            ("ADJUSTMENT_IN", "Adjustment increase"),
                            ("ADJUSTMENT_OUT", "Adjustment decrease"),
                            ("WRITE_OFF", "Write-off / damaged"),
                            ("OPENING", "Opening stock"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.SmallIntegerField(help_text="+1 inbound, -1 outbound"),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Weighted-average cost at movement time.",
                        max_digits=18,
                    ),
                ),
                ("total_cost", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "balance_quantity_after",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "balance_value_after",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "average_cost_after",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("source_object_id", models.BigIntegerField(blank=True, null=True)),
                ("source_doc_type", models.CharField(blank=True, max_length=4)),
                ("source_doc_number", models.CharField(blank=True, max_length=32)),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "stock_movement",
                "ordering": ["movement_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                ("document_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("POSTED", "Posted"),
                            ("PARTIAL", "Partially fulfilled / partially paid"),
                            ("COMPLETED", "Completed / paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REVERSED", "Reversed / credited"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "total_cost_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "stock_transfer",
                "ordering": ["-document_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StockTransferLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField()),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
            ],
            options={
                "db_table": "stock_transfer_line",
                "ordering": ["transfer", "line_no"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True)),
                (
                    "allow_negative_stock",
                    models.BooleanField(
                        default=False,
                        help_text="Overrides Company policy for this warehouse (BR-017).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "warehouse",
                "ordering": ["code"],
            },
        ),
    ]
