# Generated by Django 5.2.17 on 2026-09-02 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('purchases', '0002_humanise_help_text'),
        ('sales', '0002_humanise_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='The sales order this delivery fulfils. Leave empty only for an authorised direct delivery with no order behind it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='sales.salesorder'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='The purchase order this receipt fulfils. Leave empty only for an authorised direct receipt with no order behind it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchases.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='allow_negative_stock',
            field=models.BooleanField(default=False, help_text='Let stock go below zero at this warehouse, overriding the company-wide setting. Use only where stock is counted after the fact.'),
        ),
    ]
