# Generated by Django 5.1.15 on 2026-08-30 08:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpeningBalanceBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("as_of_date", models.DateField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_posted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "opening_balance_batch",
                "ordering": ["-as_of_date"],
            },
        ),
        migrations.CreateModel(
            name="PostingLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_object_id", models.BigIntegerField()),
                ("source_doc_type", models.CharField(blank=True, max_length=4)),
                ("source_doc_number", models.CharField(blank=True, max_length=32)),
                (
                    "effect_type",
                    models.CharField(
                        choices=[
                            ("JOURNAL", "Journal entry"),
                            ("STOCK", "Stock movement"),
                        ],
                        max_length=8,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=120, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "posting_link",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=150)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset"),
                            ("LIABILITY", "Liability"),
                            ("EQUITY", "Equity"),
                            ("INCOME", "Income"),
                            ("EXPENSE", "Expense"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        choices=[
                            ("CURRENT_ASSET", "Current asset"),
                            ("NONCURRENT_ASSET", "Non-current asset"),
                            ("CURRENT_LIABILITY", "Current liability"),
                            ("NONCURRENT_LIABILITY", "Non-current liability"),
                            ("EQUITY", "Equity"),
                            ("REVENUE", "Revenue"),
                            ("OTHER_INCOME", "Other income"),
                            ("COGS", "Cost of goods sold"),
                            ("OPERATING_EXPENSE", "Operating expense"),
                            ("OTHER_EXPENSE", "Other expense"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "normal_balance",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")], max_length=6
                    ),
                ),
                ("is_postable", models.BooleanField(default=True)),
                (
                    "is_control",
                    models.BooleanField(
                        default=False,
                        help_text="Backed by a subledger (AR/AP/Inventory). Postable only via services (GL-011).",
                    ),
                ),
                (
                    "control_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AR", "Accounts receivable"),
                            ("AP", "Accounts payable"),
                            ("INVENTORY", "Inventory"),
                            ("OUTPUT_TAX", "Output tax"),
                            ("INPUT_TAX", "Input tax"),
                            ("CASH_BANK", "Cash and bank"),
                            ("CUSTOMER_ADVANCE", "Customer advances"),
                            ("VENDOR_ADVANCE", "Vendor advances"),
                        ],
                        help_text="Names which subledger backs this control account, so the GL-011 reconciliation can pair GL balances with subledger totals without hard-coding account codes. Adopted from the colleague's schema.",
                        max_length=18,
                    ),
                ),
                (
                    "is_contra",
                    models.BooleanField(
                        default=False,
                        help_text="Carries the opposite balance to its type — sales returns and discounts (debit-natured income), purchase returns and discounts (credit-natured expense). Reports net these against their parent group (RPT-001).",
                    ),
                ),
                (
                    "requires_party",
                    models.BooleanField(
                        default=False,
                        help_text="AR/AP lines must carry a party for the subledger to reconcile.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set only for single-currency accounts such as a foreign bank account.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="ledger.account",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "account",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AccountMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("ACCOUNTS_RECEIVABLE", "Accounts receivable (control)"),
                            ("ACCOUNTS_PAYABLE", "Accounts payable (control)"),
                            (
                                "CUSTOMER_ADVANCE",
                                "Customer advances / unapplied credit",
                            ),
                            ("VENDOR_ADVANCE", "Vendor advances / prepayments"),
                            ("INVENTORY", "Inventory (control)"),
                            ("GOODS_IN_TRANSIT", "Goods received not invoiced"),
                            ("COGS", "Cost of goods sold"),
                            ("SALES_REVENUE", "Sales revenue"),
                            ("SALES_RETURNS", "Sales returns and allowances"),
                            ("SALES_DISCOUNT", "Sales discounts granted"),
                            ("PURCHASE_EXPENSE", "Non-stock purchase expense"),
                            ("PURCHASE_RETURNS", "Purchase returns and allowances"),
                            ("PURCHASE_DISCOUNT", "Purchase discounts received"),
                            ("OUTPUT_TAX", "Output tax payable"),
                            ("INPUT_TAX", "Input tax recoverable"),
                            ("TAX_NON_RECOVERABLE", "Non-recoverable tax expense"),
                            ("FX_GAIN", "Realised FX gain"),
                            ("FX_LOSS", "Realised FX loss"),
                            ("ROUNDING_GAIN", "Rounding income"),
                            ("ROUNDING_LOSS", "Rounding expense"),
                            ("INVENTORY_GAIN", "Inventory adjustment gain"),
                            ("INVENTORY_LOSS", "Inventory adjustment loss / write-off"),
                            ("RETAINED_EARNINGS", "Retained earnings"),
                            ("CURRENT_YEAR_RESULT", "Current-year profit or loss"),
                            ("OPENING_BALANCE_EQUITY", "Opening balance equity"),
                            ("STOCK_TRANSFER_CLEARING", "Stock transfer clearing"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mappings",
                        to="ledger.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "account_mapping",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                ("entry_date", models.DateField()),
                (
                    "journal_type",
                    models.CharField(
                        choices=[
                            ("SALES", "Sales"),
                            ("PURCHASE", "Purchase"),
                            ("CASH", "Cash and bank"),
                            ("INVENTORY", "Inventory"),
                            ("GENERAL", "Manual journal"),
                            ("OPENING", "Opening balance"),
                            ("CLOSING", "Period / year close"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("POSTED", "Posted"), ("REVERSED", "Reversed")],
                        default="POSTED",
                        max_length=8,
                    ),
                ),
                ("narration", models.TextField(blank=True)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1"), max_digits=18
                    ),
                ),
                (
                    "total_debit_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_credit_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("source_object_id", models.BigIntegerField(blank=True, null=True)),
                ("source_doc_type", models.CharField(blank=True, max_length=4)),
                ("source_doc_number", models.CharField(blank=True, max_length=32)),
                (
                    "idempotency_key",
                    models.CharField(default=uuid.uuid4, max_length=120, unique=True),
                ),
                ("is_reversal", models.BooleanField(default=False)),
                ("reversal_reason", models.TextField(blank=True)),
                ("is_manual", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
                (
                    "fiscal_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to="core.fiscalperiod",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_journals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reverses",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "journal entries",
                "db_table": "journal_entry",
                "ordering": ["-entry_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "debit_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "credit_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "debit_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "credit_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1"), max_digits=18
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_lines",
                        to="ledger.account",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
            ],
            options={
                "db_table": "journal_line",
                "ordering": ["entry", "line_no"],
            },
        ),
    ]
