# Generated by Django 5.1.15 on 2026-08-30 08:56

import apps.core.expressions
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0003_initial"),
        ("inventory", "0002_initial"),
        ("ledger", "0001_initial"),
        ("parties", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="journalline",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="parties.customer",
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lines",
                to="ledger.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="money_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="payments.moneyaccount",
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="tax_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.taxcode",
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="parties.vendor",
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="journal_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opening_batch",
                to="ledger.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="openingbalancebatch",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postinglink",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posting_links",
                to="ledger.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="postinglink",
            name="source_content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="postinglink",
            name="stock_movement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posting_links",
                to="inventory.stockmovement",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["account_type", "code"], name="ix_account_type_code"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["is_postable", "is_active"], name="ix_account_selectable"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="account_not_self_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("code"),
                name="account_code_unique_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_control", True),
                        models.Q(("control_type", ""), _negated=True),
                    ),
                    models.Q(("is_control", False), ("control_type", "")),
                    _connector="OR",
                ),
                name="account_control_needs_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_contra", False),
                        models.Q(
                            models.Q(
                                ("account_type__in", ["ASSET", "EXPENSE"]),
                                ("normal_balance", "DEBIT"),
                            ),
                            models.Q(
                                ("account_type__in", ["LIABILITY", "EQUITY", "INCOME"]),
                                ("normal_balance", "CREDIT"),
                            ),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        ("is_contra", True),
                        models.Q(
                            models.Q(
                                ("account_type__in", ["ASSET", "EXPENSE"]),
                                ("normal_balance", "CREDIT"),
                            ),
                            models.Q(
                                ("account_type__in", ["LIABILITY", "EQUITY", "INCOME"]),
                                ("normal_balance", "DEBIT"),
                            ),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="account_normal_balance_matches_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("account_type", "ASSET"),
                        ("subtype__in", ["CURRENT_ASSET", "NONCURRENT_ASSET"]),
                    ),
                    models.Q(
                        ("account_type", "LIABILITY"),
                        ("subtype__in", ["CURRENT_LIABILITY", "NONCURRENT_LIABILITY"]),
                    ),
                    models.Q(("account_type", "EQUITY"), ("subtype", "EQUITY")),
                    models.Q(
                        ("account_type", "INCOME"),
                        ("subtype__in", ["REVENUE", "OTHER_INCOME"]),
                    ),
                    models.Q(
                        ("account_type", "EXPENSE"),
                        ("subtype__in", ["COGS", "OPERATING_EXPENSE", "OTHER_EXPENSE"]),
                    ),
                    _connector="OR",
                ),
                name="account_subtype_matches_type",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["entry_date"], name="ix_je_date"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["fiscal_period", "entry_date"], name="ix_je_period_date"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["source_content_type", "source_object_id"], name="ix_je_source"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["source_doc_type", "source_doc_number"], name="ix_je_doc"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["journal_type", "entry_date"], name="ix_je_type_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_debit_base", models.F("total_credit_base"))),
                name="journal_entry_balanced",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_debit_base__gte", 0), ("total_credit_base__gte", 0)
                ),
                name="journal_entry_totals_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)),
                name="journal_entry_rate_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_reversal", False), ("reverses__isnull", False), _connector="OR"
                ),
                name="journal_entry_reversal_has_origin",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_manual", False),
                    models.Q(
                        ("source_content_type__isnull", True), ("source_doc_type", "")
                    ),
                    _connector="OR",
                ),
                name="journal_entry_manual_has_no_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_content_type__isnull", True),
                        ("source_object_id__isnull", True),
                    ),
                    models.Q(
                        ("source_content_type__isnull", False),
                        ("source_object_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="journal_entry_source_pair",
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(fields=["account", "entry"], name="ix_jl_account_entry"),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(fields=["customer"], name="ix_jl_customer"),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(fields=["vendor"], name="ix_jl_vendor"),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(fields=["money_account"], name="ix_jl_money_account"),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(fields=["product"], name="ix_jl_product"),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(fields=["tax_code"], name="ix_jl_tax_code"),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.UniqueConstraint(
                fields=("entry", "line_no"), name="journal_line_unique_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("debit_base__gte", 0),
                    ("credit_base__gte", 0),
                    ("debit_txn__gte", 0),
                    ("credit_txn__gte", 0),
                ),
                name="journal_line_amounts_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("debit_base__gt", 0), ("credit_base", 0)),
                    models.Q(("credit_base__gt", 0), ("debit_base", 0)),
                    _connector="OR",
                ),
                name="journal_line_debit_xor_credit",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("debit_base__gt", 0), ("credit_txn", 0)),
                    models.Q(("credit_base__gt", 0), ("debit_txn", 0)),
                    _connector="OR",
                ),
                name="journal_line_txn_side_matches_base",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)),
                name="journal_line_rate_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.LessThanOrEqual(
                    apps.core.expressions.NumNonnulls(
                        models.F("customer"), models.F("vendor")
                    ),
                    models.Value(1),
                ),
                name="journal_line_single_party",
            ),
        ),
        migrations.AddIndex(
            model_name="postinglink",
            index=models.Index(
                fields=["source_content_type", "source_object_id"],
                name="ix_posting_link_source",
            ),
        ),
        migrations.AddIndex(
            model_name="postinglink",
            index=models.Index(
                fields=["source_doc_type", "source_doc_number"],
                name="ix_posting_link_doc",
            ),
        ),
        migrations.AddIndex(
            model_name="postinglink",
            index=models.Index(
                fields=["journal_entry"], name="ix_posting_link_journal"
            ),
        ),
        migrations.AddIndex(
            model_name="postinglink",
            index=models.Index(fields=["stock_movement"], name="ix_posting_link_stock"),
        ),
        migrations.AddConstraint(
            model_name="postinglink",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.Exact(
                    apps.core.expressions.NumNonnulls(
                        models.F("journal_entry"), models.F("stock_movement")
                    ),
                    models.Value(1),
                ),
                name="posting_link_exactly_one_effect",
            ),
        ),
        migrations.AddConstraint(
            model_name="postinglink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("effect_type", "JOURNAL"), ("journal_entry__isnull", False)
                    ),
                    models.Q(
                        ("effect_type", "STOCK"), ("stock_movement__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="posting_link_effect_matches_target",
            ),
        ),
    ]
