# Generated by Django 5.2.17 on 2026-09-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_posting_guards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_control',
            field=models.BooleanField(default=False, help_text='This account is driven by a subledger - receivables, payables or inventory - so entries reach it through those workflows rather than by direct posting.'),
        ),
    ]
