# Generated by Django 5.2.17 on 2026-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_humanise_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmapping',
            name='key',
            field=models.CharField(choices=[('ACCOUNTS_RECEIVABLE', 'Accounts receivable (control)'), ('ACCOUNTS_PAYABLE', 'Accounts payable (control)'), ('CUSTOMER_ADVANCE', 'Customer advances / unapplied credit'), ('VENDOR_ADVANCE', 'Vendor advances / prepayments'), ('INVENTORY', 'Inventory (control)'), ('GOODS_IN_TRANSIT', 'Goods received not invoiced'), ('COGS', 'Cost of goods sold'), ('SALES_REVENUE', 'Sales revenue'), ('SALES_RETURNS', 'Sales returns and allowances'), ('SALES_DISCOUNT', 'Sales discounts granted'), ('PURCHASE_EXPENSE', 'Non-stock purchase expense'), ('PURCHASE_RETURNS', 'Purchase returns and allowances'), ('PURCHASE_DISCOUNT', 'Purchase discounts received'), ('OUTPUT_TAX', 'Output tax payable'), ('INPUT_TAX', 'Input tax recoverable'), ('TAX_NON_RECOVERABLE', 'Non-recoverable tax expense'), ('FX_GAIN', 'Realised FX gain'), ('FX_LOSS', 'Realised FX loss'), ('ROUNDING_GAIN', 'Rounding income'), ('ROUNDING_LOSS', 'Rounding expense'), ('MERCHANT_FEE', 'Merchant and payment-processor fees'), ('INVENTORY_GAIN', 'Inventory adjustment gain'), ('INVENTORY_LOSS', 'Inventory adjustment loss / write-off'), ('RETAINED_EARNINGS', 'Retained earnings'), ('CURRENT_YEAR_RESULT', 'Current-year profit or loss'), ('OPENING_BALANCE_EQUITY', 'Opening balance equity'), ('STOCK_TRANSFER_CLEARING', 'Stock transfer clearing')], max_length=32, unique=True),
        ),
    ]
