# Generated by Django 5.1.15 on 2026-08-30 08:56

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("barcode", models.CharField(blank=True, max_length=64)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("STOCK", "Stocked item"),
                            ("NON_STOCK", "Non-stock item"),
                            ("SERVICE", "Service"),
                        ],
                        default="STOCK",
                        max_length=10,
                    ),
                ),
                ("is_inventory", models.BooleanField(default=True)),
                (
                    "sales_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "max_discount_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("100"), max_digits=9
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "product",
                "ordering": ["sku"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "product categories",
                "db_table": "product_category",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("SALES", "Sales"), ("PURCHASE", "Purchase")],
                        default="SALES",
                        max_length=8,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "product_price",
                "ordering": ["product", "kind", "-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("decimal_places", models.PositiveSmallIntegerField(default=2)),
                (
                    "ratio_to_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1"), max_digits=18
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "unit_of_measure",
                "ordering": ["code"],
            },
        ),
    ]
