# Generated by Django 5.1.15 on 2026-08-30 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0002_initial"),
        ("ledger", "0001_initial"),
        ("parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cogs_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ledger.account",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="default_purchase_tax_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.taxcode",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="default_sales_tax_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.taxcode",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="expense_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ledger.account",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="inventory_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ledger.account",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="preferred_vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="parties.vendor",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="revenue_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ledger.account",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="cogs_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ledger.account",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="inventory_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ledger.account",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="catalog.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="revenue_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ledger.account",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="productprice",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.currency",
            ),
        ),
        migrations.AddField(
            model_name="productprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="unitofmeasure",
            name="base_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="derived_units",
                to="catalog.unitofmeasure",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.unitofmeasure",
            ),
        ),
        migrations.AddConstraint(
            model_name="productcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parent__isnull", True),
                    models.Q(("parent", models.F("id")), _negated=True),
                    _connector="OR",
                ),
                name="product_category_not_self_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="productprice",
            index=models.Index(
                fields=["product", "kind", "currency", "-valid_from"],
                name="ix_product_price_lookup",
            ),
        ),
        migrations.AddConstraint(
            model_name="productprice",
            constraint=models.UniqueConstraint(
                fields=("product", "kind", "currency", "min_quantity", "valid_from"),
                name="product_price_unique_point",
            ),
        ),
        migrations.AddConstraint(
            model_name="productprice",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)), name="product_price_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="productprice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="product_price_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="unitofmeasure",
            constraint=models.CheckConstraint(
                condition=models.Q(("ratio_to_base__gt", 0)), name="uom_ratio_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="unitofmeasure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("base_unit__isnull", True),
                    models.Q(("base_unit", models.F("id")), _negated=True),
                    _connector="OR",
                ),
                name="uom_not_self_base",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="ix_product_name"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["barcode"], name="ix_product_barcode"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "sku"], name="ix_product_selectable"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="ix_product_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("sales_price__gte", 0), ("purchase_price__gte", 0)),
                name="product_prices_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("reorder_level__gte", 0)),
                name="product_reorder_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_discount_percent__gte", 0), ("max_discount_percent__lte", 100)
                ),
                name="product_max_discount_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("product_type", "STOCK"), ("is_inventory", False), _connector="OR"
                ),
                name="product_nonstock_not_inventory",
            ),
        ),
    ]
