# Generated by Django 5.1.15 on 2026-08-30 08:56

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0002_initial"),
        ("inventory", "0001_initial"),
        ("ledger", "0001_initial"),
        ("parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                ("document_date", models.DateField(db_index=True)),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "posting_date",
                    models.DateField(
                        help_text="Ledger date; must fall inside an open fiscal period (BR-020)."
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1"), max_digits=18
                    ),
                ),
                (
                    "subtotal_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "line_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "document_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "rounding_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "subtotal_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "line_discount_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "document_discount_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "rounding_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "allocated_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "credited_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "open_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "open_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("POSTED", "Posted"),
                            ("PARTIAL", "Partially fulfilled / partially paid"),
                            ("COMPLETED", "Completed / paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REVERSED", "Reversed / credited"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_reason", models.CharField(blank=True, max_length=255)),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("vendor_reference", models.CharField(blank=True, max_length=64)),
                ("delivery_address_text", models.TextField(blank=True)),
                (
                    "document_discount_kind",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("PERCENT", "Percentage"),
                            ("AMOUNT", "Fixed amount"),
                        ],
                        default="NONE",
                        max_length=8,
                    ),
                ),
                (
                    "document_discount_value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
                (
                    "fiscal_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.fiscalperiod",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.paymentterm",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="parties.vendor",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order",
                "ordering": ["-document_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                ("document_date", models.DateField(db_index=True)),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "posting_date",
                    models.DateField(
                        help_text="Ledger date; must fall inside an open fiscal period (BR-020)."
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1"), max_digits=18
                    ),
                ),
                (
                    "subtotal_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "line_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "document_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "rounding_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "subtotal_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "line_discount_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "document_discount_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "rounding_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "allocated_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "credited_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "open_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "open_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("POSTED", "Posted"),
                            ("PARTIAL", "Partially fulfilled / partially paid"),
                            ("COMPLETED", "Completed / paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REVERSED", "Reversed / credited"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_reason", models.CharField(blank=True, max_length=255)),
                ("vendor_invoice_number", models.CharField(max_length=64)),
                ("vendor_invoice_date", models.DateField(blank=True, null=True)),
                (
                    "duplicate_override_reason",
                    models.CharField(blank=True, max_length=255),
                ),
                ("vendor_name_snapshot", models.CharField(blank=True, max_length=200)),
                ("vendor_tax_id_snapshot", models.CharField(blank=True, max_length=50)),
                ("billing_address_text", models.TextField(blank=True)),
                (
                    "document_discount_kind",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("PERCENT", "Percentage"),
                            ("AMOUNT", "Fixed amount"),
                        ],
                        default="NONE",
                        max_length=8,
                    ),
                ),
                (
                    "document_discount_value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                ("is_reversed", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
                (
                    "fiscal_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.fiscalperiod",
                    ),
                ),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="inventory.goodsreceipt",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "payable_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.account",
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.paymentterm",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="parties.vendor",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bills",
                        to="purchases.purchaseorder",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_bill",
                "ordering": ["-document_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                (
                    "line_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "allocated_document_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_rate_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                ("tax_is_inclusive", models.BooleanField(default=False)),
                ("tax_is_recoverable", models.BooleanField(default=True)),
                (
                    "gross_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "net_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "net_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "quantity_received",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "quantity_billed",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "quantity_cancelled",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchases.purchaseorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.taxcode",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.unitofmeasure",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_order_line",
                "ordering": ["order", "line_no"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseBillLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                (
                    "line_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "allocated_document_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_rate_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                ("tax_is_inclusive", models.BooleanField(default=False)),
                ("tax_is_recoverable", models.BooleanField(default=True)),
                (
                    "gross_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "net_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "net_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("is_stock_line", models.BooleanField(default=True)),
                ("product_sku_snapshot", models.CharField(blank=True, max_length=40)),
                (
                    "quantity_returned",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchases.purchasebill",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.account",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "receipt_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill_lines",
                        to="inventory.goodsreceiptline",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.taxcode",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.unitofmeasure",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "purchase_order_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="purchases.purchaseorderline",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_bill_line",
                "ordering": ["bill", "line_no"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                ("document_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("POSTED", "Posted"),
                            ("PARTIAL", "Partially fulfilled / partially paid"),
                            ("COMPLETED", "Completed / paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REVERSED", "Reversed / credited"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField(help_text="Mandatory (RET-008).")),
                (
                    "total_cost_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "original_bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="purchases.purchasebill",
                    ),
                ),
                (
                    "original_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="inventory.goodsreceipt",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="parties.vendor",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_return",
                "ordering": ["-document_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReturnLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField()),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "disposition",
                    models.CharField(
                        choices=[
                            ("RESTOCK", "Return to saleable stock"),
                            ("WRITE_OFF", "Damaged / write-off"),
                            ("NO_STOCK_EFFECT", "No stock effect"),
                        ],
                        default="RESTOCK",
                        max_length=16,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "bill_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="purchases.purchasebillline",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "purchase_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchases.purchasereturn",
                    ),
                ),
                (
                    "receipt_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="inventory.goodsreceiptline",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_return_line",
                "ordering": ["purchase_return", "line_no"],
            },
        ),
        migrations.CreateModel(
            name="VendorDebitNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                ("document_date", models.DateField(db_index=True)),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "posting_date",
                    models.DateField(
                        help_text="Ledger date; must fall inside an open fiscal period (BR-020)."
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1"), max_digits=18
                    ),
                ),
                (
                    "subtotal_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "line_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "document_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "rounding_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "subtotal_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "line_discount_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "document_discount_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "rounding_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "allocated_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "credited_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "open_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "open_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("POSTED", "Posted"),
                            ("PARTIAL", "Partially fulfilled / partially paid"),
                            ("COMPLETED", "Completed / paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REVERSED", "Reversed / credited"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_reason", models.CharField(blank=True, max_length=255)),
                (
                    "vendor_credit_reference",
                    models.CharField(blank=True, max_length=64),
                ),
                ("reason", models.TextField(help_text="Mandatory (RET-008).")),
                ("vendor_name_snapshot", models.CharField(blank=True, max_length=200)),
                (
                    "refunded_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("is_reversed", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
                (
                    "fiscal_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.fiscalperiod",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "original_bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debit_notes",
                        to="purchases.purchasebill",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_return",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debit_notes",
                        to="purchases.purchasereturn",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debit_notes",
                        to="parties.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_debit_note",
                "ordering": ["-document_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VendorDebitNoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                (
                    "line_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "allocated_document_discount_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_rate_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=9
                    ),
                ),
                ("tax_is_inclusive", models.BooleanField(default=False)),
                ("tax_is_recoverable", models.BooleanField(default=True)),
                (
                    "gross_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "net_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_txn",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "net_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable_base_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "tax_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "total_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("is_stock_line", models.BooleanField(default=True)),
                (
                    "bill_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debit_lines",
                        to="purchases.purchasebillline",
                    ),
                ),
                (
                    "debit_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchases.vendordebitnote",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ledger.account",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "return_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="purchases.purchasereturnline",
                    ),
                ),
                (
                    "tax_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.taxcode",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.unitofmeasure",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_debit_note_line",
                "ordering": ["debit_note", "line_no"],
            },
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["vendor", "-document_date"], name="ix_po_vendor_date"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["status", "-document_date"], name="ix_po_status_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)), name="po_rate_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_txn__gte", 0), ("total_base__gte", 0)),
                name="po_total_nonneg",
            ),
        ),
        migrations.AddIndex(
            model_name="purchasebill",
            index=models.Index(
                fields=["vendor", "-document_date"], name="ix_pb_vendor_date"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasebill",
            index=models.Index(fields=["status", "due_date"], name="ix_pb_status_due"),
        ),
        migrations.AddIndex(
            model_name="purchasebill",
            index=models.Index(fields=["posting_date"], name="ix_pb_posting_date"),
        ),
        migrations.AddIndex(
            model_name="purchasebill",
            index=models.Index(
                condition=models.Q(("open_txn__gt", 0)),
                fields=["vendor", "due_date"],
                name="ix_pb_open_items",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasebill",
            constraint=models.UniqueConstraint(
                fields=("vendor", "vendor_invoice_number"),
                name="pb_vendor_invoice_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasebill",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)), name="pb_rate_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasebill",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_txn__gte", 0), ("total_base__gte", 0)),
                name="pb_total_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasebill",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allocated_txn__gte", 0),
                    ("credited_txn__gte", 0),
                    ("allocated_txn__lte", models.F("total_txn")),
                    ("credited_txn__lte", models.F("total_txn")),
                ),
                name="pb_settlement_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasebill",
            constraint=models.CheckConstraint(
                condition=models.Q(("open_txn__gte", 0)), name="pb_open_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasebill",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "open_txn",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("total_txn"), "-", models.F("allocated_txn")
                            ),
                            "-",
                            models.F("credited_txn"),
                        ),
                    )
                ),
                name="pb_open_is_derived",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasebill",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["POSTED", "PARTIAL", "COMPLETED", "REVERSED"]),
                        _negated=True,
                    ),
                    ("journal_entry__isnull", False),
                    _connector="OR",
                ),
                name="pb_posted_has_journal",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasebill",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("due_date__isnull", True),
                    ("due_date__gte", models.F("document_date")),
                    _connector="OR",
                ),
                name="pb_due_after_document_date",
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorderline",
            index=models.Index(fields=["product"], name="ix_po_line_product"),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.UniqueConstraint(
                fields=("order", "line_no"), name="po_line_unique_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="po_line_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)), name="po_line_price_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity_received__gte", 0), ("quantity_billed__gte", 0)
                ),
                name="po_line_progress_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_percent__gte", 0), ("discount_percent__lte", 100)
                ),
                name="po_line_discount_range",
            ),
        ),
        migrations.AddIndex(
            model_name="purchasebillline",
            index=models.Index(fields=["product"], name="ix_pb_line_product"),
        ),
        migrations.AddIndex(
            model_name="purchasebillline",
            index=models.Index(fields=["tax_code"], name="ix_pb_line_tax"),
        ),
        migrations.AddConstraint(
            model_name="purchasebillline",
            constraint=models.UniqueConstraint(
                fields=("bill", "line_no"), name="pb_line_unique_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasebillline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="pb_line_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasebillline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)), name="pb_line_price_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasebillline",
            constraint=models.CheckConstraint(
                condition=models.Q(("line_discount_txn__lte", models.F("gross_txn"))),
                name="pb_line_discount_within_gross",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasebillline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity_returned__gte", 0),
                    ("quantity_returned__lte", models.F("quantity")),
                ),
                name="pb_line_returned_within_billed",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasebillline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_stock_line", True), ("product__isnull", False)),
                    models.Q(
                        ("is_stock_line", False), ("expense_account__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="pb_line_target_present",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasebillline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tax_rate_percent__gte", 0), ("tax_rate_percent__lte", 100)
                ),
                name="pb_line_tax_rate_range",
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereturn",
            index=models.Index(
                fields=["vendor", "-document_date"], name="ix_pr_vendor_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasereturn",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("original_bill__isnull", False),
                    ("original_receipt__isnull", False),
                    _connector="OR",
                ),
                name="purchase_return_has_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasereturn",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason", ""), _negated=True),
                name="purchase_return_reason_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasereturnline",
            constraint=models.UniqueConstraint(
                fields=("purchase_return", "line_no"), name="pr_line_unique_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasereturnline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="pr_line_qty_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="vendordebitnote",
            index=models.Index(
                fields=["vendor", "-document_date"], name="ix_dbn_vendor_date"
            ),
        ),
        migrations.AddIndex(
            model_name="vendordebitnote",
            index=models.Index(
                condition=models.Q(("open_txn__gt", 0)),
                fields=["vendor"],
                name="ix_dbn_open_credit",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendordebitnote",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_rate__gt", 0)), name="dbn_rate_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendordebitnote",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_txn__gte", 0)), name="dbn_total_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendordebitnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allocated_txn__gte", 0),
                    ("refunded_txn__gte", 0),
                    ("allocated_txn__lte", models.F("total_txn")),
                    ("refunded_txn__lte", models.F("total_txn")),
                ),
                name="dbn_settlement_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendordebitnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "open_txn",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("total_txn"), "-", models.F("allocated_txn")
                            ),
                            "-",
                            models.F("refunded_txn"),
                        ),
                    )
                ),
                name="dbn_open_is_derived",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendordebitnote",
            constraint=models.CheckConstraint(
                condition=models.Q(("open_txn__gte", 0)), name="dbn_open_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendordebitnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["POSTED", "PARTIAL", "COMPLETED", "REVERSED"]),
                        _negated=True,
                    ),
                    ("journal_entry__isnull", False),
                    _connector="OR",
                ),
                name="dbn_posted_has_journal",
            ),
        ),
        migrations.AddIndex(
            model_name="vendordebitnoteline",
            index=models.Index(fields=["product"], name="ix_dbn_line_product"),
        ),
        migrations.AddConstraint(
            model_name="vendordebitnoteline",
            constraint=models.UniqueConstraint(
                fields=("debit_note", "line_no"), name="dbn_line_unique_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendordebitnoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="dbn_line_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendordebitnoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tax_rate_percent__gte", 0), ("tax_rate_percent__lte", 100)
                ),
                name="dbn_line_tax_rate_range",
            ),
        ),
    ]
