# Generated by Django 5.2.17 on 2026-09-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='posting_date',
            field=models.DateField(help_text='The date this document hits the ledger. It must fall inside an open fiscal period, and it can differ from the document date.'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='posting_date',
            field=models.DateField(help_text='The date this document hits the ledger. It must fall inside an open fiscal period, and it can differ from the document date.'),
        ),
        migrations.AlterField(
            model_name='vendordebitnote',
            name='posting_date',
            field=models.DateField(help_text='The date this document hits the ledger. It must fall inside an open fiscal period, and it can differ from the document date.'),
        ),
    ]
